apiVersion: v1
kind: Secret
metadata:
  name: shortener-secret
type: Opaque
stringData:
  ADMIN_TOKEN: ""   # Реальный Secret создаётся командой: kubectl create secret generic shortener-secret --from-env-file=.env