apiVersion: v1
kind: Service
metadata:
  name: shortener-service      # новое имя
spec:
  selector:
    app: url-shortener          # ← должно совпадать с labels в deployment.yaml
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080